# When a JWT token is about to expire, a notification is sent by this JWT authorization extension to the client to renew
# its JWT token. The notification is sent to the client in advance with the number of seconds configured by this
# parameter before the JWT token expiry.
renewTokenBeforeSeconds=60
